# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f40f27defac321bd0b5b3c47e4bd1b1ad3796c6a711420b8a2ca0ab72c73d6c530fb3df0c3a055ea443d85f87e7ced2a46fd7a69c9df13ed841c59ea38f2735

test:
  secret_key_base: 7a0eab26ddd0b4f8196db352d5dd9a6999404c6ed66d5520fd4c737dfe5829e0585b2968817746d84d55d6eff2e2a5dd39454e286409fb6dfb3729681190a137

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
